#!/usr/bin/env python
# -*- coding: utf8 -*-

from upyun import UpYun,md5,md5file
import sys, os
import os.path

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser(description="又拍云python客户端")
    parser.add_argument("-b", "--bucket", type = str, default ="", help = "又拍云桶名")
    parser.add_argument("-u", "--username", type = str, default ="", help = "操作员用户名")
    parser.add_argument("-p", "--password", type = str, default ="", help = "操作员密码")
    parser.add_argument("-r", "--recursion", action = 'store_true', default = True, help = "是否递归子目录")
    parser.add_argument("path", help = "需要上传的目录")
    parser.add_argument("tpath", help = "目标目录")

    args = parser.parse_args(sys.argv[1:])
    kwargs = vars(args)

    if kwargs["bucket"]:
        bucket = kwargs["bucket"]
    else:
        bucket = raw_input("请输入又拍云桶名:\n")

    if kwargs["username"]:
        username = kwargs["username"]
    else:
        username = raw_input("请输入操作员用户名:\n")

    if kwargs["password"]:
        password = kwargs["password"]
    else:
        password = raw_input("请输入操作员密码:\n")

    u = UpYun(bucket, username, password)

    path = kwargs["path"]
    tpath = kwargs["tpath"]

    for root, dirs, files in os.walk(path):
        for f in files:
            data = open(os.path.join(root, f), 'rb')
            u.setContentMD5(md5file(data))
            upfp = os.path.join(tpath, os.path.relpath(os.path.join(root, f), path))
            a = u.writeFile(upfp, data, True)
            print a
        if ".git" in dirs:
            dirs.remove(".git")
        if not kwargs["recursion"]:
            del dirs[0:len(dirs)]
